# Generated by Django 5.0 on 2023-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serialno', models.CharField(max_length=100)),
                ('sensor_type_id', models.IntegerField()),
                ('aqs_system_serialno', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensor',
            },
        ),
    ]
