# Generated by Django 4.2.6 on 2023-12-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table='aqs.sensor',
        ),
    ]
