# Generated by Django 4.2.6 on 2024-01-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aqunit',
            table='aqs.aq_unit',
        ),
    ]
