# Generated by Django 4.2.6 on 2024-01-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_aqunit_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'managed': False, 'verbose_name': 'aqs.measurement', 'verbose_name_plural': 'aqs.measurements'},
        ),
    ]
