# Generated by Django 5.0 on 2023-12-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sensor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
