# Generated by Django 4.2.6 on 2024-01-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_measurement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aqunit',
            options={'managed': False, 'verbose_name': 'aqs.aq_unit', 'verbose_name_plural': 'aqs.aq_units'},
        ),
        migrations.AlterModelOptions(
            name='aqunittype',
            options={'managed': False, 'verbose_name': 'aqs.aq_unit_type', 'verbose_name_plural': 'aqs.aq_unit_types'},
        ),
    ]
