# Generated by Django 5.0.1 on 2024-01-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_aqunit_options_alter_aqunittype_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggerconfig',
            table='aqs.logger_config',
        ),
    ]
