# Generated by Django 5.0.1 on 2024-01-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_loggerconfig_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggerconfig',
            table='logger_config',
        ),
    ]
