# Generated by Django 5.0.1 on 2024-01-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_loggerconfig_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggerconfig',
            table='aqs_logger_config',
        ),
    ]
