# Generated by Django 5.0.1 on 2024-01-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_loggerconfig_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'managed': False, 'verbose_name': 'measurement', 'verbose_name_plural': 'measurements'},
        ),
        migrations.AlterModelOptions(
            name='measurementpointtype',
            options={'managed': False, 'verbose_name': 'measurement_pt_type', 'verbose_name_plural': 'measurement_pt_types'},
        ),
    ]
