# Generated by Django 5.0.1 on 2024-01-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementpointtype',
            options={'managed': False, 'verbose_name': 'Measurement Point Type', 'verbose_name_plural': 'Measurement Point Types'},
        ),
        migrations.AlterModelTable(
            name='measurementpointtype',
            table='aqs_measurement_pt_type',
        ),
    ]
