# Generated by Django 5.0.1 on 2024-01-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_measurementpointtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurementpointtype',
            table='"aqs"."measurement_pt_type"',
        ),
    ]
