# Generated by Django 5.0.1 on 2024-01-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_measurementpointtype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='"aqs"."measurement"',
        ),
    ]
