# Generated by Django 5.0.1 on 2024-01-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_measurement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurementpoint',
            table='"aqs"."measurement_pt"',
        ),
    ]
