# Generated by Django 5.0.1 on 2024-01-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_measurementpoint_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aqunit',
            table='"aqs"."aq_unit"',
        ),
    ]
