# Generated by Django 5.0.1 on 2024-01-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_aqunit_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggerconfig',
            table='"aqs"."logger_config"',
        ),
    ]
