# Generated by Django 5.0.1 on 2024-01-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_loggerconfig_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aqsmodel',
            options={'verbose_name': 'Aqs Model', 'verbose_name_plural': 'Aqs Models'},
        ),
        migrations.AlterModelOptions(
            name='aqssystem',
            options={'verbose_name': 'Aqs System', 'verbose_name_plural': 'Aqs Systems'},
        ),
        migrations.AlterModelOptions(
            name='aqunit',
            options={'verbose_name': 'aqs.aq_unit', 'verbose_name_plural': 'aqs.aq_units'},
        ),
        migrations.AlterModelOptions(
            name='aqunittype',
            options={'verbose_name': 'aqs.aq_unit_type', 'verbose_name_plural': 'aqs.aq_unit_types'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='loggerconfig',
            options={'verbose_name': 'Logger Configuration', 'verbose_name_plural': 'Logger Configurations'},
        ),
        migrations.AlterModelOptions(
            name='loggerinstance',
            options={'verbose_name': 'Logger Instance', 'verbose_name_plural': 'Logger Instances'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'measurement', 'verbose_name_plural': 'measurements'},
        ),
        migrations.AlterModelOptions(
            name='measurementpoint',
            options={'verbose_name': 'Measurement Point', 'verbose_name_plural': 'Measurement Points'},
        ),
        migrations.AlterModelOptions(
            name='measurementpointevent',
            options={'verbose_name': 'Measurement Point Event', 'verbose_name_plural': 'Measurement Point Events'},
        ),
        migrations.AlterModelOptions(
            name='measurementpointhistory',
            options={'verbose_name': 'Measurement Point History', 'verbose_name_plural': 'Measurement Point Histories'},
        ),
        migrations.AlterModelOptions(
            name='measurementpointsensor',
            options={'verbose_name': 'Measurement Point Sensor', 'verbose_name_plural': 'Measurement Point Sensors'},
        ),
        migrations.AlterModelOptions(
            name='measurementpointtype',
            options={'verbose_name': 'Measurement Point Type', 'verbose_name_plural': 'Measurement Point Types'},
        ),
        migrations.AlterModelOptions(
            name='mqtttopic',
            options={'verbose_name': 'MQTT Topic', 'verbose_name_plural': 'MQTT Topics'},
        ),
        migrations.AlterModelOptions(
            name='oemmanufacturer',
            options={'verbose_name': 'OEM Manufacturer', 'verbose_name_plural': 'OEM Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='sensorhistory',
            options={'verbose_name': 'Sensor History', 'verbose_name_plural': 'Sensor Histories'},
        ),
        migrations.AlterModelOptions(
            name='sensortype',
            options={'verbose_name': 'Sensor Type', 'verbose_name_plural': 'Sensor Types'},
        ),
        migrations.AlterModelOptions(
            name='sensorverification',
            options={'verbose_name': 'Sensor Verification', 'verbose_name_plural': 'Sensor Verifications'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='sitecontact',
            options={'verbose_name': 'Site Contact', 'verbose_name_plural': 'Site Contacts'},
        ),
        migrations.AlterModelOptions(
            name='tagname',
            options={'verbose_name': 'Tag Name', 'verbose_name_plural': 'Tag Names'},
        ),
        migrations.AlterModelOptions(
            name='tagtype',
            options={'verbose_name': 'Tag Type', 'verbose_name_plural': 'Tag Types'},
        ),
        migrations.AlterModelOptions(
            name='versioninfo',
            options={'verbose_name': 'Version Information', 'verbose_name_plural': 'Version Information'},
        ),
    ]
