 # Use an official Python runtime as a parent image
 FROM python:3.8

 # Set environment varibles
 ENV PYTHONUNBUFFERED=1

 # Set work directory in the container
 WORKDIR /path/in/container

 # Copy requirements file into the container
 COPY requirements.txt .

 # Install dependencies
 RUN pip install -r requirements.txt

 # Copy the current directory contents into the container
 COPY . .


# # Use the official Python image from the DockerHub
# FROM python:3.10-slim

# # Set the working directory in docker
# WORKDIR /app

# # Copy the dependencies file to the working directory
# COPY requirements.txt .

# # Install any dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy the content of the local src directory to the working directory
# COPY . .

# # Specify the command to run on container start
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# FROM postgres:latest
# ENV POSTGRES_DB=postgres
# ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=postgres
